version: '3.7'

services:
    jenkinss5:
        image: jenkins/jenkins:lts
        container_name: jenkinss5
        privileged: true
        user: root
        networks:
          - jenkins-net
        restart: always
        ports:
        - 8080:8080
        - 50000:50000
        volumes:
          - jenkins-log:/var/log/jenkins
          - jenkins-data:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
    nginxs5:
        build: ./jenkins-nginx
        container_name: nginxs5
        links:
          - jenkinss5
        volumes:
          - ./nginx/conf.d:/etc/nginx/conf.d
          - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
        - 80:80
        - 443:443
#        restart: always
#        depends_on:
#        - jenkinss5
        networks:
          - jenkins-net

networks:
  jenkins-net:

volumes:
  jenkins-log:
  jenkins-data:
