version: '3.7'

services:
    jenkinss5:
        image: docker.io/bitnami/jenkins:2
        container_name: jenkinss5
        networks:
          - jenkins-net
        restart: always
        ports:
        - 8080:8080
        volumes:
          - jenkins-log:/var/log/jenkins
          - jenkins-data:/var/jenkins_home
    nginxs5:
        build: ./jenkins-nginx
        container_name: nginxs5
        volumes:
           - type: bind
             source: ./jenkins-nginx/nginx.conf
             target: /etc/nginx/conf.d/default.conf
        ports:
        - 80:80
        - 443:443
        restart: always
        networks:
          - jenkins-net

networks:
  jenkins-net:

volumes:
  jenkins-log:
  jenkins-data:
