version: '3.7'

services:
    jenkinss5:
        image: docker.io/bitnami/jenkins
        container_name: jenkinss5
        networks:
          - jenkins-net
        restart: always
        ports:
        - 8080:8080
        - 50000:50000
        volumes:
          - jenkins-log:/var/log/jenkins
          - jenkins-data:/var/jenkins_home
    nginxs5:
        build: ./jenkins-nginx
        container_name: nginxs5
        links:
          - jenkinss5
#        volumes:
#          - type: bind
#            source: ./jenkins-nginx/nginx.conf
#            target: /etc/nginx/conf.d/default.conf
        ports:
        - 80:80
        - 443:443
        restart: always
        depends_on:
        - jenkinss5
        networks:
          - jenkins-net

networks:
  jenkins-net:

volumes:
  jenkins-log:
  jenkins-data:
